### ISSUE TITLE
Support for smart groups (via saved searches)

### ISSUE THREAD

**Issue by johanv** [CiviCooP/org.civicoop.configitems#1]
It would be nice if this extension would be able to load smart groups. I guess this can be done by adding saved search support.

**Comment by ErikHommel** [comment]
I guess so too @johanv :-) Care to add this?

**Comment by johanv** [comment]
I will see if I can find some time :-)

**Comment by johanv** [comment]
I've been working on this:
https://github.com/CiviCooP/org.iida.civiconfig/compare/master...johanv:1-smart_groups?expand=1

It partially works. Problem is that the saved search is created over and over again. I guess I might have to fix a bug in the SavedSearch.get API (which I wrote myself, I'm afraid ;-)); searching on form_values does not seem to work for SavedSearches.
