### ISSUE TITLE
creating a custom group for participants for event types

### ISSUE THREAD

**Issue by JO0st** [CiviCooP/org.civicoop.configitems#15]
Creating a custom group for participants for events of a certain type does not work. This is because the API expects the value for the event type and not the id of the option value. An example custom_groups.json is:

```json
{
  "Test_config":{
    "name": "test_config",
    "title": "test_config",
    "extends": "ParticipantEventType",
    "extends_entity_column_value": ["AB", "SB"],
    "style": "inline",
    "collapse_display" : 0,
    "weight" : 1,
    "is_active" : 1,
    "fields":{
      "participant_information_ctesl":{
        "name" : "participant_information_test",
        "label" : "test",
        "data_type" : "Boolean",
        "html_type" : "Radio",
        "default_value" : 0,
        "is_required" : 1,
        "is_searchable" : "1",
        "weight" : 3,
        "is_active" : 1
      }
    }
  }
}
```

**Comment by jaapjansma** [comment]
That is because the id of the option value could be different in different environments. The value should be the same across all environments. Does specifying the value work for you?

**Comment by jaapjansma** [comment]
The example at Roparun works at the moment: https://github.com/CiviCooP/nl.roparun.generic/blob/master/resources/custom_groups.json

**Comment by JO0st** [comment]
Specifying the value works for us. In the roparun example there is no ParticipantEventType extension, and this is the problematic one for us.

**Comment by JO0st** [comment]
I just noticed that it was a mistake on our patched version. I didn't know our version of configitems was patched. Sorry for the mistake.

**Comment by jaapjansma** [comment]
Ah I see what you mean. Are you a developer? 

If so you can add the code for eventtype here: https://github.com/CiviCooP/org.civicoop.configitems/blob/master/CRM/Civiconfig/Entity/CustomGroup.php#L179

**Comment by jaapjansma** [comment]
Ah ok. Shall I close the issue?

**Comment by JO0st** [comment]
I was using this one: https://github.com/CiviCooP/org.civicoop.configitems/blob/0a805a72671130417144bfe883d9a08e78da4944/CRM/Civiconfig/Entity/CustomGroup.php#L158

Yes i'm a developper.

**Comment by JO0st** [comment]
Our patches are in this pull request: https://github.com/CiviCooP/org.civicoop.configitems/pull/13. I will remark the mistake i found in it in the pull request.
